# Generated by Django 4.0.4 on 2022-07-27 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qbank', '0002_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice1', models.CharField(max_length=50, unique=True)),
                ('choice2', models.CharField(max_length=50, unique=True)),
                ('choice3', models.CharField(max_length=50, unique=True)),
                ('choice4', models.CharField(max_length=50, unique=True)),
                ('answer_key', models.IntegerField()),
                ('answer_value', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default='False')),
                ('score', models.IntegerField(default=0)),
                ('negative_score', models.IntegerField(default=0)),
                ('sequence', models.IntegerField(default=0)),
                ('is_correct_answer', models.BooleanField(default='False')),
                ('question_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qbank.question')),
            ],
        ),
    ]
