# Generated by Django 4.0.4 on 2022-07-27 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qbank', '0003_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cateory_name',
            new_name='name',
        ),
    ]
